module.exports = (pathname) => {
  if (/\.aac$/.test(pathname)) return 'audio/aac'
  if (/\.oga$/.test(pathname)) return 'audio/ogg'
  if (/\.json$/.test(pathname)) return 'application/json'
  if (/\.pdf$/.test(pathname)) return 'application/pdf'
  if (/\.xml$/.test(pathname)) return 'application/xml'
  if (/\.ts$/.test(pathname)) return 'application/typescript'
  if (/\.ogx$/.test(pathname)) return 'application/ogg'
  if (/\.eot$/.test(pathname)) return 'application/vnd.ms-fontobject'
  if (/\.js$/.test(pathname)) return 'application/javascript'
  if (/\.ttf$/.test(pathname)) return 'font/ttf'
  if (/\.woff$/.test(pathname)) return 'font/woff'
  if (/\.woff2$/.test(pathname)) return 'font/woff2'
  if (/\.(jpeg|jpg)$/.test(pathname)) return 'image/jpeg'
  if (/\.png$/.test(pathname)) return 'image/png'
  if (/\.svg$/.test(pathname)) return 'image/svg+xml'
  if (/\.gif$/.test(pathname)) return 'image/gif'
  if (/\.ico$/.test(pathname)) return 'image/x-icon'
  if (/\.css$/.test(pathname)) return 'text/css'
  if (/\.csv$/.test(pathname)) return 'text/csv'
  if (/\.ics$/.test(pathname)) return 'text/calendar'
  if (/\.html?$/.test(pathname)) return 'text/html'
  if (/\.ogv$/.test(pathname)) return 'video/ogg'
  if (/\.avi$/.test(pathname)) return 'video/x-msvideo'
  return 'text/html'
}
